name: Initialize Template Repo
on:
  - push

permissions:
  contents: write

jobs:
  cleanup:
    name: "Initialize template repository"
    runs-on: ubuntu-24.04
    if: ${{ !github.event.repository.is_template }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
      - name: Install init tools
        run: |
          sudo apt-get update
          sudo apt-get install -y perl
      - name: Initialize Repo
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

          mod_name=$(echo "$GITHUB_REPOSITORY" | cut -d/ -f2)
          ./init.sh --side=both "$mod_name"

          git add .
          git commit \
            -m "Initialize template repository" \
            -m "Set mod name to $mod_name" \
            -m "Set mod side to both"
      - name: Push changes
        uses: ad-m/github-push-action@v1
        with:
          branch: ${{ github.ref }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
